sailsbooks:
  build: .
  links:
    - mysql
  ports:
    - "1337:1337"
  volumes:
    - ./:/sails
  command: npm start
  environment:
    - NODE_ENV=dev

mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: root
    MYSQL_PASSWORD: root
    MYSQL_DATABASE: sailsbooks